"""
chat.py
-------

Provides functions for loading a language model, retrieving relevant text
chunks from a vector store, and generating responses to user queries.

The module expects that ``faiss_index.bin`` and ``documents.pkl`` were
generated by ``ingest.py`` and are located in the same directory.

Usage::

    from chat import answer_query
    response = answer_query("What is the history of Kingston?")
    print(response)
"""

from __future__ import annotations

import os
import pickle
from functools import lru_cache
from typing import List

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer



@lru_cache(maxsize=1)
def _load_index_and_docs():
    """Load FAISS index and corresponding documents into memory (cached)."""
    dir_path = os.path.dirname(__file__)
    index_path = os.path.join(dir_path, "faiss_index.bin")
    docs_path = os.path.join(dir_path, "documents.pkl")
    if not os.path.exists(index_path) or not os.path.exists(docs_path):
        raise FileNotFoundError(
            "Index or documents not found. Please run ingest.py to generate them."
        )
    index = faiss.read_index(index_path)
    with open(docs_path, "rb") as f:
        documents: List[str] = pickle.load(f)
    return index, documents


@lru_cache(maxsize=1)
def _load_embedding_model() -> SentenceTransformer:
    """Load the embedding model (cached to avoid repeated downloads)."""
    return SentenceTransformer("all-MiniLM-L6-v2")


@lru_cache(maxsize=1)
def _load_llm():
    """Load the language model and tokenizer (cached)."""
    model_name = os.environ.get("LLM_MODEL", "google/flan-t5-small")
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
    return tokenizer, model


def retrieve_relevant_chunks(query: str, k: int = 4) -> List[str]:
    """Retrieve the top-k most similar text chunks for the given query.

    Args:
        query: The user query.
        k: Number of chunks to retrieve.

    Returns:
        List of text chunks ranked by similarity.
    """
    index, documents = _load_index_and_docs()
    embed_model = _load_embedding_model()
    query_vec = embed_model.encode([query])
    distances, indices = index.search(query_vec, k)
    return [documents[i] for i in indices[0]]


def generate_response(prompt: str, max_length: int = 256) -> str:
    """Generate text from the language model given a prompt."""
    tokenizer, model = _load_llm()
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model.generate(**inputs, max_length=max_length)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)


def answer_query(query: str, k: int = 8) -> str:
    """Generate an answer to ``query`` using retrieval-augmented generation.

    Args:
        query: Question asked by the user.
        k: Number of context chunks to include.

    Returns:
        The generated answer as a string.
    """
    chunks = retrieve_relevant_chunks(query, k=k)
    context = "\n\n".join(chunks)
    prompt = (
    "You are a document assistant.\n"
    "Answer the user's question using ONLY the context.\n"
    "First, identify what the document is (resume, cover letter, notes, article, etc.).\n"
    "If the context contains a person's name and education/experience sections, it is likely a resume.\n"
    "Be specific. Prefer answers like: \"This appears to be Philip Akindipe's resume\".\n"
    "If the answer is not in the context, say \"I don't know.\".\n\n"
    f"Context:\n{context}\n\n"
    f"Question:\n{query}\n\n"
    "Answer in 1-2 sentences:"
)
    answer = generate_response(prompt)

    return {
        "answer": answer.strip(),
        "sources": chunks
    }


__all__ = ["answer_query", "retrieve_relevant_chunks"]